allowBuilds:
    '@parcel/watcher': false
    esbuild: true
# The minimum age of a release to be considered for dependency installation.
# The value is in minutes (1440 minutes = 1 day).
minimumReleaseAge: 1440

nodeLinker: hoisted
